/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddServerForm: typeof import('./components/AddServerForm.vue')['default']
    AddWorldForm: typeof import('./components/AddWorldForm.vue')['default']
    EditServerForm: typeof import('./components/EditServerForm.vue')['default']
    GameBackup: typeof import('./components/GameBackup.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameDetail: typeof import('./components/GameDetail.vue')['default']
    GameDetailMainInfo: typeof import('./components/GameDetailMainInfo.vue')['default']
    GameDetailRequirenments: typeof import('./components/GameDetailRequirenments.vue')['default']
    GameStatusChip: typeof import('./components/GameStatusChip.vue')['default']
    GameWorldCard: typeof import('./components/GameWorldCard.vue')['default']
    GameWorlds: typeof import('./components/GameWorlds.vue')['default']
    LangSelector: typeof import('./components/LangSelector.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    OsCard: typeof import('./components/OsCard.vue')['default']
    ProviderCard: typeof import('./components/ProviderCard.vue')['default']
    RawHtmlText: typeof import('./components/RawHtmlText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerCard: typeof import('./components/ServerCard.vue')['default']
    ServerInfo: typeof import('./components/ServerInfo.vue')['default']
    UploadBackupForm: typeof import('./components/UploadBackupForm.vue')['default']
  }
}
